"use client";

/**
 * CssVariables — injects all global CSS (design tokens, animations, component
 * styles) via MUI GlobalStyles so emotion handles SSR properly.
 *
 * Source of truth for colors/fonts: lib/theme/tokens.ts
 */

import { GlobalStyles } from "@mui/material";
import { CSS_VAR_MAP, COLORS, FONTS } from "./tokens";

export default function CssVariables() {
  return (
    <GlobalStyles
      styles={{
        // ── Design tokens → :root CSS variables ────────────────────────────
        ":root": CSS_VAR_MAP,

        // ── Keyframe animations ─────────────────────────────────────────────
        "@keyframes fadeUp": {
          from: { opacity: 0, transform: "translateY(14px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        "@keyframes fadeIn": {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        "@keyframes spin": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "@keyframes pulse": {
          "0%, 100%": { opacity: 0.35 },
          "50%": { opacity: 0.65 },
        },
        "@keyframes dotPulse": {
          "0%, 80%, 100%": { transform: "scale(0.6)", opacity: 0.4 },
          "40%":           { transform: "scale(1.0)", opacity: 1.0 },
        },
        "@keyframes msgFadeIn": {
          from: { opacity: 0, transform: "translateY(4px)" },
          to:   { opacity: 1, transform: "translateY(0)" },
        },

        // Inline loading dots (Today page)
        "@keyframes altfitDot": {
          "0%, 80%, 100%": { transform: "scale(0.55)", opacity: 0.3 },
          "40%":           { transform: "scale(1)",    opacity: 1   },
        },

        // Cinematic outfit generating screen
        "@keyframes outfitStageFadeIn": {
          "0%":   { opacity: 0, transform: "translateY(14px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "@keyframes outfitProgress": {
          from: { width: "0%" },
          to:   { width: "85%" },
        },

        // Upload card animations
        "@keyframes scanline": {
          "0%":   { transform: "translateY(-100%)", opacity: 0 },
          "10%":  { opacity: 1 },
          "90%":  { opacity: 1 },
          "100%": { transform: "translateY(700%)", opacity: 0 },
        },
        "@keyframes uploadShimmer": {
          from: { backgroundPosition: "-200% center" },
          to:   { backgroundPosition:  "200% center" },
        },
        "@keyframes uploadFadeIn": {
          from: { opacity: 0, transform: "translateY(8px)" },
          to:   { opacity: 1, transform: "translateY(0)" },
        },
        // Wardrobe item shimmer — used for analysisStatus: "pending" cards
        "@keyframes shimmerMove": {
          "0%":   { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },

        // ── Utility classes ─────────────────────────────────────────────────
        ".fade-up": { animation: "fadeUp 0.5s ease forwards" },
        ".fade-in": { animation: "fadeIn 0.4s ease forwards" },

        // ── App shell ───────────────────────────────────────────────────────
        ".app": { minHeight: "100vh", background: `var(--cream)` },

        // ── Desktop sidebar nav ─────────────────────────────────────────────
        ".nav": {
          position: "fixed",
          top: 0,
          left: 0,
          width: 240,
          height: "100vh",
          background: COLORS.ink,
          display: "flex",
          flexDirection: "column",
          padding: "36px 0 24px",
          zIndex: 300,
          borderRight: "1px solid rgba(255,255,255,0.05)",
          transform: "translateX(-100%)",
          transition: "transform 0.28s cubic-bezier(0.4,0,0.2,1)",
        },
        ".nav.nav-open": {
          transform: "translateX(0)",
        },
        ".nav-overlay": {
          display: "none",
          position: "fixed",
          inset: 0,
          background: "rgba(46,33,24,0.48)",
          zIndex: 299,
          animation: "fadeIn 0.2s ease",
        },
        ".nav-overlay.nav-open": {
          display: "block",
        },
        // ── Hamburger button (mobile only) ──────────────────────────────────
        ".hamburger-btn": {
          display: "flex",
          flexDirection: "column",
          gap: 5,
          width: 34,
          height: 34,
          alignItems: "center",
          justifyContent: "center",
          background: "none",
          border: "none",
          cursor: "pointer",
          padding: 0,
          flexShrink: 0,
        },
        ".hamburger-line": {
          display: "block",
          width: 20,
          height: 1,
          background: COLORS.ink,
          transition: "opacity 0.2s",
        },
        ".nav-logo": {
          fontFamily: FONTS.serif,
          fontSize: 15,
          fontWeight: 300,
          letterSpacing: "0.28em",
          textTransform: "uppercase",
          color: COLORS.cream,
          padding: "0 28px",
          marginBottom: 44,
          cursor: "pointer",
          display: "block",
          border: "none",
          background: "none",
          textAlign: "left",
        },
        ".nav-logo span": { color: COLORS.gold },

        ".nav-links": {
          flex: 1,
          display: "flex",
          flexDirection: "column",
          gap: 2,
          padding: "0 14px",
        },
        ".nav-link": {
          display: "flex",
          alignItems: "center",
          padding: "12px 14px",
          fontFamily: FONTS.sans,
          fontSize: 10,
          fontWeight: 400,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: "rgba(247,243,236,0.42)",
          background: "none",
          border: "none",
          borderLeft: "2px solid transparent",
          cursor: "pointer",
          textAlign: "left",
          width: "100%",
          transition: "color 0.2s, background 0.2s, border-color 0.2s",
        },
        ".nav-link:hover": {
          color: "rgba(247,243,236,0.8)",
          background: "rgba(255,255,255,0.04)",
        },
        ".nav-link.active": {
          color: COLORS.cream,
          borderLeftColor: COLORS.gold,
          background: "rgba(255,255,255,0.065)",
        },

        ".nav-bottom": {
          padding: "16px 14px 0",
          borderTop: "1px solid rgba(255,255,255,0.08)",
          display: "flex",
          flexDirection: "column",
          gap: 10,
        },
        ".nav-upload": {
          display: "block",
          width: "100%",
          padding: "11px 14px",
          background: COLORS.gold,
          color: COLORS.cream,
          border: "none",
          fontFamily: FONTS.sans,
          fontSize: 10,
          fontWeight: 500,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          cursor: "pointer",
          transition: "background 0.2s",
          textAlign: "center",
        },
        ".nav-upload:hover": { background: COLORS.goldLight },

        ".nav-profile-btn": {
          display: "flex",
          alignItems: "center",
          gap: 10,
          padding: "10px 0",
          background: "none",
          border: "none",
          cursor: "pointer",
          width: "100%",
          textAlign: "left",
        },
        ".nav-avatar": {
          width: 28,
          height: 28,
          borderRadius: "50%",
          background: "rgba(255,255,255,0.12)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontFamily: FONTS.serif,
          fontSize: 13,
          color: COLORS.cream,
          flexShrink: 0,
          border: "none",
        },
        ".nav-user-name": {
          fontFamily: FONTS.sans,
          fontSize: 11,
          fontWeight: 400,
          color: "rgba(247,243,236,0.85)",
          lineHeight: 1.3,
        },
        ".nav-user-plan": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.1em",
          textTransform: "uppercase",
          color: COLORS.gold,
          marginTop: 1,
        },
        ".nav-signout": {
          display: "block",
          padding: "6px 0",
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: "rgba(247,243,236,0.3)",
          background: "none",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
          transition: "color 0.2s",
        },
        ".nav-signout:hover": { color: "rgba(247,243,236,0.65)" },

        // ── Mobile top bar ──────────────────────────────────────────────────
        ".mobile-topbar": {
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          height: 56,
          background: COLORS.cream,
          borderBottom: `1px solid ${COLORS.linen}`,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "0 20px",
          zIndex: 100,
        },
        ".mobile-logo": {
          fontFamily: FONTS.serif,
          fontSize: 14,
          fontWeight: 300,
          letterSpacing: "0.28em",
          textTransform: "uppercase",
          color: COLORS.ink,
        },
        ".mobile-logo span": { color: COLORS.gold },

        // ── Mobile tab bar ──────────────────────────────────────────────────
        ".tab-bar": {
          position: "fixed",
          bottom: 0,
          left: 0,
          right: 0,
          height: 64,
          paddingBottom: "env(safe-area-inset-bottom)",
          background: COLORS.cream,
          borderTop: `1px solid ${COLORS.linen}`,
          display: "flex",
          alignItems: "center",
          zIndex: 100,
        },
        ".tab-item": {
          flex: 1,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          gap: 4,
          padding: "8px 0",
          background: "none",
          border: "none",
          cursor: "pointer",
          color: COLORS.taupe,
          transition: "color 0.2s",
        },
        ".tab-item.active": { color: COLORS.ink },
        ".tab-icon": { fontSize: 18, lineHeight: 1 },
        ".tab-label": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.12em",
          textTransform: "uppercase",
        },
        ".tab-upload-btn": {
          flex: 1,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "none",
          border: "none",
          cursor: "pointer",
        },
        ".tab-upload-inner": {
          width: 44,
          height: 44,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: 22,
          fontWeight: 300,
          color: COLORS.cream,
          transition: "background 0.2s",
        },

        // ── Page layout (base — mobile first) ──────────────────────────────
        ".page": {
          minHeight: "100vh",
          paddingTop: 56,
          paddingBottom: 80,
        },

        // ── Page header (shared: wardrobe, upload) ──────────────────────────
        ".page-header": {
          padding: "32px 20px 24px",
          borderBottom: `1px solid ${COLORS.linen}`,
        },
        ".page-eyebrow": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          fontWeight: 400,
          letterSpacing: "0.2em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          marginBottom: 10,
        },
        ".page-title": {
          fontFamily: FONTS.serif,
          fontSize: 38,
          fontWeight: 300,
          color: COLORS.ink,
          lineHeight: 1.05,
          marginBottom: 4,
        },
        ".page-count": {
          fontFamily: FONTS.sans,
          fontSize: 12,
          color: COLORS.warmGray,
          marginTop: 4,
        },

        // ── Common buttons ──────────────────────────────────────────────────
        ".btn-primary": {
          flex: "1 1 0",
          padding: "13px 20px",
          background: COLORS.ink,
          color: COLORS.cream,
          border: "none",
          fontFamily: FONTS.sans,
          fontSize: 10,
          fontWeight: 500,
          letterSpacing: "0.16em",
          textTransform: "uppercase",
          cursor: "pointer",
          transition: "background 0.2s, transform 0.15s cubic-bezier(0.4,0,0.2,1), box-shadow 0.15s",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
        },
        ".btn-primary:hover": {
          background: COLORS.charcoal,
          transform: "translateY(-1px)",
          boxShadow: "0 4px 18px rgba(46,33,24,0.16)",
        },
        ".btn-primary:active": {
          transform: "translateY(0) scale(0.98)",
          boxShadow: "none",
        },
        ".btn-primary:disabled": {
          background: COLORS.linen,
          color: COLORS.taupe,
          cursor: "not-allowed",
          transform: "none",
          boxShadow: "none",
        },
        ".btn-secondary": {
          flex: "1 1 0",
          padding: "13px 20px",
          background: "none",
          color: COLORS.charcoal,
          border: `1px solid ${COLORS.linen}`,
          fontFamily: FONTS.sans,
          fontSize: 10,
          fontWeight: 400,
          letterSpacing: "0.16em",
          textTransform: "uppercase",
          cursor: "pointer",
          transition: "border-color 0.2s, color 0.2s, transform 0.15s",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
        },
        ".btn-secondary:hover": {
          borderColor: COLORS.charcoal,
          color: COLORS.ink,
        },
        ".btn-secondary:active": {
          transform: "scale(0.98)",
        },

        // ── Auth / Landing hero (mobile) ────────────────────────────────────
        ".landing-hero": {
          padding: "48px 24px 32px 24px",
          display: "flex",
          flexDirection: "column",
          gap: 16,
        },
        ".landing-brand": {
          fontSize: 11,
          letterSpacing: "0.25em",
          color: COLORS.gold,
          fontWeight: 600,
          marginBottom: 4,
          fontFamily: FONTS.sans,
          textTransform: "uppercase",
        },
        ".landing-headline": {
          fontFamily: FONTS.serif,
          fontSize: 38,
          lineHeight: 1.15,
          color: COLORS.ink,
          margin: 0,
          fontWeight: 400,
        },
        ".landing-subtext": {
          fontSize: 15,
          lineHeight: 1.6,
          color: "#7a7060",
          margin: 0,
          maxWidth: 320,
          fontFamily: FONTS.sans,
          fontWeight: 300,
        },
        ".landing-proof": {
          display: "flex",
          alignItems: "center",
          gap: 20,
          paddingTop: 16,
          paddingBottom: 16,
          marginTop: 8,
        },
        ".proof-item": {
          display: "flex",
          flexDirection: "column",
          gap: 2,
        },
        ".proof-number": {
          fontFamily: FONTS.serif,
          fontSize: 22,
          color: COLORS.ink,
          lineHeight: 1,
        },
        ".proof-label": {
          fontSize: 10,
          color: "#9a8f80",
          letterSpacing: "0.05em",
          fontFamily: FONTS.sans,
        },
        ".proof-divider": {
          width: 1,
          height: 32,
          background: "rgba(201,169,110,0.25)",
          flexShrink: 0,
        },
        ".auth-section": {
          padding: "0 24px 48px 24px",
          display: "flex",
          flexDirection: "column",
          gap: 12,
        },
        ".auth-label": {
          fontFamily: FONTS.sans,
          fontSize: 10,
          letterSpacing: "0.15em",
          color: COLORS.gold,
          margin: "0 0 4px 0",
          textTransform: "uppercase",
        },
        ".btn-create": {
          width: "100%",
          padding: "17px",
          background: COLORS.ink,
          color: COLORS.sand,
          border: "none",
          borderRadius: "12px",
          fontFamily: FONTS.sans,
          fontSize: 14,
          fontWeight: 600,
          letterSpacing: "0.1em",
          textTransform: "uppercase",
          cursor: "pointer",
          transition: "opacity 0.15s ease",
        },
        ".btn-create:active": { transform: "scale(0.98)", opacity: 0.9 },
        ".btn-signin": {
          width: "100%",
          padding: "16px",
          background: "transparent",
          color: "#5a5040",
          border: "1px solid rgba(0,0,0,0.1)",
          borderRadius: "12px",
          fontFamily: FONTS.sans,
          fontSize: 14,
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          cursor: "pointer",
        },
        ".auth-divider": {
          display: "flex",
          alignItems: "center",
          gap: 12,
          color: "#9a8f80",
          fontSize: 12,
          fontFamily: FONTS.sans,
        },
        ".auth-divider::before, .auth-divider::after": {
          content: "''",
          flex: 1,
          height: 1,
          background: "rgba(0,0,0,0.08)",
        },
        ".auth-terms": {
          fontFamily: FONTS.sans,
          fontSize: 11,
          color: "#9a8f80",
          textAlign: "center",
          margin: "4px 0 0 0",
          lineHeight: 1.5,
        },
        ".btn-shuffle": {
          width: 44,
          height: 44,
          background: "none",
          border: `1px solid ${COLORS.linen}`,
          cursor: "pointer",
          fontSize: 18,
          color: COLORS.taupe,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          transition: "all 0.2s",
          flexShrink: 0,
        },
        ".btn-shuffle:hover": {
          borderColor: COLORS.taupe,
          color: COLORS.charcoal,
        },
        ".btn-shuffle.spinning": { animation: "spin 0.8s linear infinite" },

        // ── Today page ──────────────────────────────────────────────────────
        ".today-hero": {
          display: "flex",
          flexDirection: "column",
        },
        ".today-greeting": {
          padding: "28px 20px 32px",
          borderBottom: `1px solid ${COLORS.linen}`,
        },
        ".greeting-eyebrow": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          fontWeight: 400,
          letterSpacing: "0.22em",
          textTransform: "uppercase",
          color: COLORS.gold,
          marginBottom: 16,
        },
        ".greeting-title": {
          fontFamily: FONTS.serif,
          fontSize: "clamp(32px, 7vw, 46px)",
          fontWeight: 300,
          lineHeight: 1.15,
          color: COLORS.ink,
          marginBottom: 14,
        },
        ".greeting-title em": { fontStyle: "italic", color: COLORS.gold },
        ".greeting-sub": {
          fontFamily: FONTS.sans,
          fontSize: 13,
          color: COLORS.warmGray,
          lineHeight: 1.6,
          marginBottom: 20,
        },
        ".weather-pill": {
          display: "inline-flex",
          alignItems: "center",
          gap: 8,
          padding: "6px 14px",
          border: `1px solid ${COLORS.linen}`,
          fontFamily: FONTS.sans,
          fontSize: 11,
          color: COLORS.charcoal,
          marginBottom: 28,
        },

        // ── Today greeting header ────────────────────────────────────────────
        ".today-greeting-header": {
          padding: "28px 20px 32px",
          borderBottom: `1px solid ${COLORS.linen}`,
        },
        ".streak-badge": {
          display: "inline-flex",
          alignItems: "center",
          gap: "8px",
          padding: "10px 22px",
          background: COLORS.ink,
          color: COLORS.cream,
          fontFamily: FONTS.sans,
          fontSize: 11,
          fontWeight: 600,
          letterSpacing: "0.12em",
          textTransform: "uppercase",
          borderRadius: "100px",
          border: "none",
          cursor: "default",
          marginTop: "8px",
        },
        ".streak-inline": {
          fontFamily: FONTS.sans,
          fontSize: 12,
          fontWeight: 600,
          color: COLORS.gold,
          background: "rgba(201,169,110,0.1)",
          padding: "4px 12px",
          borderRadius: "100px",
          border: "1px solid rgba(201,169,110,0.2)",
        },

        // ── Outfit card ─────────────────────────────────────────────────────
        ".outfit-card": {
          border: `1px solid ${COLORS.linen}`,
          background: COLORS.cream,
        },
        ".outfit-card-header": {
          padding: "16px 20px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          borderBottom: `1px solid ${COLORS.linen}`,
        },
        ".outfit-card-title": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: COLORS.taupe,
        },
        ".occasion-tag": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.1em",
          textTransform: "uppercase",
          padding: "3px 8px",
          border: `1px solid ${COLORS.linen}`,
          color: COLORS.charcoal,
        },
        ".outfit-pieces": {
          display: "grid",
          gap: "1px",
          background: COLORS.linen,
        },
        ".outfit-piece": {
          background: COLORS.cream,
          overflow: "hidden",
        },
        ".piece-visual": {
          aspectRatio: "3/4",
          maxHeight: 160,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          position: "relative",
          overflow: "hidden",
          background: COLORS.paper,
        },
        ".piece-label": {
          padding: "10px 12px 2px",
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: COLORS.taupe,
        },
        ".piece-name": {
          padding: "2px 12px 12px",
          fontFamily: FONTS.serif,
          fontSize: 14,
          color: COLORS.charcoal,
          lineHeight: 1.3,
        },
        ".outfit-reasoning": {
          padding: "14px 20px",
          display: "flex",
          gap: 10,
          background: COLORS.paper,
          borderTop: `1px solid ${COLORS.linen}`,
        },
        ".reasoning-icon": {
          color: COLORS.gold,
          fontSize: 10,
          flexShrink: 0,
          marginTop: 3,
          lineHeight: 1.6,
        },
        ".reasoning-text": {
          fontFamily: FONTS.serif,
          fontSize: 14,
          fontStyle: "italic",
          color: COLORS.charcoal,
          lineHeight: 1.56,
        },
        ".outfit-actions": {
          padding: "14px 20px",
          display: "flex",
          gap: 8,
          borderTop: `1px solid ${COLORS.linen}`,
        },

        // ── Style sidebar ───────────────────────────────────────────────────
        ".today-sidebar": {
          background: COLORS.paper,
          borderTop: `1px solid ${COLORS.linen}`,
          animation: "fadeIn 0.4s ease forwards",
          opacity: 0,
        },
        ".sidebar-section": {
          padding: "24px 20px",
          borderBottom: `1px solid ${COLORS.linen}`,
        },
        ".sidebar-heading": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.2em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          marginBottom: 16,
        },
        ".style-score-bar": {
          display: "flex",
          flexDirection: "column",
          gap: 12,
        },
        ".score-item": {
          display: "flex",
          alignItems: "center",
          gap: 10,
        },
        ".score-label": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          color: COLORS.warmGray,
          width: 64,
          flexShrink: 0,
        },
        ".score-track": {
          flex: 1,
          height: 2,
          background: COLORS.linen,
          position: "relative",
          overflow: "hidden",
        },
        ".score-fill": {
          position: "absolute",
          left: 0,
          top: 0,
          bottom: 0,
          background: COLORS.gold,
          transition: "width 0.6s ease",
        },
        ".insight-card": {
          background: COLORS.cream,
          padding: 16,
          borderLeft: `2px solid ${COLORS.gold}`,
        },
        ".insight-label": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.12em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          marginBottom: 6,
        },
        ".insight-text": {
          fontFamily: FONTS.sans,
          fontSize: 12,
          color: COLORS.charcoal,
          lineHeight: 1.5,
        },
        ".last-worn-list": {
          display: "flex",
          flexDirection: "column",
          gap: 10,
        },
        ".last-worn-item": { display: "flex", alignItems: "center", gap: 10 },
        ".last-worn-dot": {
          width: 8,
          height: 8,
          borderRadius: "50%",
          flexShrink: 0,
        },
        ".last-worn-name": {
          flex: 1,
          fontFamily: FONTS.sans,
          fontSize: 12,
          color: COLORS.charcoal,
        },
        ".last-worn-date": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          color: COLORS.taupe,
        },

        // ── Wardrobe page ───────────────────────────────────────────────────
        ".filter-bar": {
          display: "flex",
          alignItems: "center",
          gap: 8,
          padding: "16px 20px",
          borderBottom: `1px solid ${COLORS.linen}`,
          overflowX: "auto",
          scrollbarWidth: "none",
          msOverflowStyle: "none",
          position: "sticky",
          top: 0,
          zIndex: 20,
          background: "rgba(245,240,232,0.96)",
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
        },
        ".filter-bar::-webkit-scrollbar": { display: "none" },
        ".filter-label": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          marginRight: 4,
          flexShrink: 0,
        },
        ".filter-chip": {
          padding: "6px 14px",
          border: `1px solid ${COLORS.linen}`,
          background: "none",
          fontFamily: FONTS.sans,
          fontSize: 10,
          letterSpacing: "0.1em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          cursor: "pointer",
          transition: "all 0.2s",
          whiteSpace: "nowrap",
          flexShrink: 0,
        },
        ".filter-chip:hover": {
          borderColor: COLORS.taupe,
          color: COLORS.charcoal,
        },
        ".filter-chip.active": {
          background: COLORS.ink,
          borderColor: COLORS.ink,
          color: COLORS.cream,
        },
        ".wardrobe-grid": {
          display: "grid",
          gridTemplateColumns: "repeat(2, 1fr)",
          columnGap: "12px",
          rowGap: "20px",
          background: COLORS.cream,
          padding: "0 16px 24px",
        },
        ".wardrobe-item": {
          position: "relative",
          cursor: "pointer",
          background: COLORS.cream,
          overflow: "hidden",
          borderRadius: 4,
          animation: "fadeUp 0.4s ease forwards",
          opacity: 0,
        },
        ".item-image": {
          aspectRatio: "4/5",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          position: "relative",
          overflow: "hidden",
          background: COLORS.paper,
        },
        ".item-info": {
          padding: "5px 0 0",
          background: COLORS.cream,
        },
        ".item-type": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.10em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          marginBottom: 1,
          lineHeight: 1.3,
        },
        ".item-name": {
          fontFamily: FONTS.sans,
          fontSize: 11,
          fontVariant: "small-caps",
          fontWeight: 500,
          letterSpacing: "0.08em",
          color: COLORS.ink,
          lineHeight: 1.25,
        },
        ".item-meta": {
          display: "flex",
          gap: 6,
          flexWrap: "wrap",
          marginTop: 2,
        },
        ".wear-count": {
          fontFamily: FONTS.sans,
          fontSize: 10,
          color: COLORS.warmGray,
          letterSpacing: "0.04em",
        },
        ".item-tag": {
          fontFamily: FONTS.sans,
          fontSize: 10,
          letterSpacing: "0.04em",
          textTransform: "uppercase",
          color: COLORS.warmGray,
        },
        ".item-overlay": { display: "none" },
        ".item-overlay-text": { display: "none" },

        // ── Wardrobe item modal ─────────────────────────────────────────────
        ".modal-backdrop": {
          position: "fixed",
          inset: 0,
          background: "rgba(46,33,24,0.52)",
          display: "flex",
          alignItems: "flex-end",
          justifyContent: "center",
          zIndex: 200,
          animation: "fadeIn 0.2s ease",
        },
        ".modal": {
          background: COLORS.cream,
          width: "100%",
          maxHeight: "90vh",
          overflowY: "auto",
          animation: "fadeUp 0.28s ease",
        },
        ".modal-header": {
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "space-between",
          padding: "22px 20px 16px",
          borderBottom: `1px solid ${COLORS.linen}`,
          position: "sticky",
          top: 0,
          background: COLORS.cream,
          zIndex: 1,
        },
        ".modal-close": {
          background: "none",
          border: "none",
          fontSize: 22,
          cursor: "pointer",
          color: COLORS.taupe,
          lineHeight: 1,
          padding: 0,
          width: 28,
          height: 28,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          transition: "color 0.15s",
          flexShrink: 0,
        },
        ".modal-close:hover": { color: COLORS.ink },
        ".modal-body": {
          display: "flex",
          flexDirection: "column",
        },
        ".modal-image": {
          minHeight: 220,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          position: "relative",
          overflow: "hidden",
          background: COLORS.paper,
          borderBottom: `1px solid ${COLORS.linen}`,
        },
        ".modal-details": {
          padding: "20px",
          display: "flex",
          flexDirection: "column",
          gap: 20,
        },
        ".detail-block-label": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          marginBottom: 10,
        },
        ".styling-note": {
          background: COLORS.paper,
          padding: 16,
          borderLeft: `2px solid ${COLORS.gold}`,
        },
        ".pairing-chips": { display: "flex", flexWrap: "wrap", gap: 6 },
        ".pairing-chip": {
          padding: "4px 10px",
          border: `1px solid ${COLORS.linen}`,
          fontFamily: FONTS.sans,
          fontSize: 10,
          letterSpacing: "0.06em",
          textTransform: "uppercase",
          color: COLORS.charcoal,
        },
        ".wear-dots": { display: "flex", gap: 4 },
        ".wear-dot": {
          width: 6,
          height: 6,
          borderRadius: "50%",
          background: COLORS.ink,
        },
        ".wear-dot.empty": { background: COLORS.linen },

        // ── Upload page ─────────────────────────────────────────────────────
        ".upload-body": {
          padding: "28px 20px",
          display: "flex",
          flexDirection: "column",
          gap: 16,
        },
        ".upload-zone": {
          display: "block",
          border: `1px dashed ${COLORS.taupe}`,
          padding: "52px 32px",
          textAlign: "center",
          background: "transparent",
          cursor: "pointer",
          transition: "border-color 0.2s, background 0.2s",
        },
        ".upload-zone:hover": {
          borderColor: COLORS.gold,
          background: "rgba(160,98,44,0.03)",
        },
        ".upload-zone.dragover": {
          borderColor: COLORS.gold,
          background: "rgba(160,98,44,0.03)",
        },
        ".upload-icon": {
          fontSize: 28,
          color: COLORS.taupe,
          marginBottom: 14,
          fontWeight: 300,
          lineHeight: 1,
        },
        ".upload-title": {
          fontFamily: FONTS.serif,
          fontSize: 20,
          fontWeight: 300,
          color: COLORS.ink,
          marginBottom: 8,
        },
        ".upload-sub": {
          fontFamily: FONTS.sans,
          fontSize: 12,
          color: COLORS.warmGray,
          lineHeight: 1.6,
        },
        ".progress-bar": {
          height: 1,
          background: COLORS.linen,
          overflow: "hidden",
        },
        ".progress-fill": {
          height: "100%",
          background: COLORS.gold,
          transition: "width 0.3s ease",
        },

        ".upload-zone-inner": {
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: 12,
          pointerEvents: "none",
        },
        ".upload-camera-icon": {
          fontSize: 36,
          color: COLORS.taupe,
          marginBottom: 4,
        },
        ".upload-cta-pill": {
          display: "inline-block",
          padding: "8px 22px",
          background: COLORS.ink,
          color: COLORS.cream,
          fontFamily: FONTS.sans,
          fontSize: 11,
          letterSpacing: "0.16em",
          textTransform: "uppercase",
        },
        ".upload-desktop-hint": {
          fontFamily: FONTS.sans,
          fontSize: 11,
          color: COLORS.taupe,
          letterSpacing: "0.04em",
        },
        // Upload item cards list
        ".upload-item-card": {
          display: "flex",
          alignItems: "center",
          gap: 14,
          padding: "12px 16px",
          background: COLORS.cream,
          border: `1px solid ${COLORS.linen}`,
          animation: "uploadFadeIn 0.3s ease forwards",
          opacity: 0,
        },
        ".upload-item-queued": { opacity: 0.65 },
        ".upload-item-analyzing": { opacity: 1 },
        ".upload-item-success": { borderColor: "rgba(160,98,44,0.3)" },
        ".upload-item-error": { borderColor: "rgba(192,57,43,0.3)" },
        ".upload-item-thumb": {
          width: 56,
          height: 56,
          flexShrink: 0,
          position: "relative",
          overflow: "hidden",
          background: COLORS.paper,
        },
        ".upload-item-thumb-img": {
          width: "100%",
          height: "100%",
          objectFit: "cover",
        },
        ".upload-item-thumb-skeleton": {
          width: "100%",
          height: "100%",
          background: `linear-gradient(90deg, ${COLORS.linen} 25%, ${COLORS.paper} 50%, ${COLORS.linen} 75%)`,
          backgroundSize: "200% 100%",
          animation: "uploadShimmer 1.4s ease infinite",
        },
        ".upload-item-thumb-scanning": { position: "relative" },
        ".upload-scan-overlay": {
          position: "absolute",
          inset: 0,
          overflow: "hidden",
          pointerEvents: "none",
        },
        ".upload-scan-line": {
          position: "absolute",
          left: 0,
          right: 0,
          height: "2px",
          background: `linear-gradient(90deg, transparent, ${COLORS.goldLight}, transparent)`,
          animation: "scanline 1.8s ease-in-out infinite",
        },
        ".upload-success-badge": {
          position: "absolute",
          bottom: 4,
          right: 4,
          width: 20,
          height: 20,
          borderRadius: "50%",
          background: COLORS.gold,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: COLORS.cream,
          boxShadow: "0 1px 4px rgba(0,0,0,0.2)",
        },
        ".upload-item-info": {
          flex: 1,
          display: "flex",
          flexDirection: "column",
          gap: 2,
          minWidth: 0,
        },
        ".upload-item-label": {
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: COLORS.taupe,
        },
        ".upload-item-label-gold": { color: COLORS.gold },
        ".upload-item-label-dim": { color: COLORS.warmGray, opacity: 0.6 },
        ".upload-item-name": {
          fontFamily: FONTS.serif,
          fontSize: 15,
          fontWeight: 300,
          color: COLORS.ink,
          lineHeight: 1.2,
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
        },
        ".upload-progress-bar": {
          height: 2,
          background: COLORS.linen,
          overflow: "hidden",
          marginTop: 6,
        },
        ".upload-progress-fill": {
          height: "100%",
          background: COLORS.gold,
          transition: "width 0.35s ease",
        },
        ".upload-item-error-icon": {
          width: 40,
          height: 40,
          flexShrink: 0,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: `1px solid rgba(192,57,43,0.35)`,
          color: COLORS.error,
          fontSize: 16,
          fontWeight: 300,
        },
        ".upload-remove-btn": {
          marginTop: 8,
          background: "none",
          border: `1px solid ${COLORS.linen}`,
          padding: "4px 12px",
          cursor: "pointer",
          fontFamily: FONTS.sans,
          fontSize: 9,
          letterSpacing: "0.1em",
          textTransform: "uppercase",
          color: COLORS.taupe,
          transition: "border-color 0.15s, color 0.15s",
          alignSelf: "flex-start",
          "&:hover": { borderColor: COLORS.taupe, color: COLORS.charcoal },
        },

        // ── Responsive: tablet / desktop ────────────────────────────────────
        "@media (min-width: 768px)": {
          ".mobile-topbar": { display: "none" },
          ".tab-bar": { display: "none" },
          ".hamburger-btn": { display: "none" },
          ".nav": { transform: "translateX(0)" },
          ".nav-overlay": { display: "none !important" },
          ".page": {
            paddingTop: 0,
            paddingBottom: 0,
            paddingLeft: 240,
          },
          ".page-header": { padding: "48px 48px 32px" },
          ".today-hero": {
            display: "grid",
            gridTemplateColumns: "1fr 296px",
            minHeight: "100vh",
            flexDirection: "unset",
          },
          ".today-greeting": {
            padding: "52px 48px 48px",
            borderBottom: "none",
            borderRight: `1px solid ${COLORS.linen}`,
          },
          ".today-sidebar": {
            borderTop: "none",
          },
          ".sidebar-section": { padding: "28px" },
          ".filter-bar": { padding: "12px 48px 16px" },
          ".wardrobe-grid": {
            gridTemplateColumns: "repeat(4, 1fr)",
            columnGap: "12px",
            rowGap: "20px",
            padding: "0 48px 32px",
          },
          ".modal-backdrop": {
            alignItems: "center",
            padding: 20,
          },
          ".modal": {
            maxWidth: 860,
            maxHeight: "calc(100vh - 40px)",
          },
          ".modal-header": { padding: "28px 32px 20px" },
          ".modal-body": {
            flexDirection: "row",
          },
          ".modal-image": {
            width: 280,
            flexShrink: 0,
            minHeight: 360,
            borderBottom: "none",
            borderRight: `1px solid ${COLORS.linen}`,
          },
          ".modal-details": { padding: "24px 32px" },
          ".upload-body": { padding: "36px 48px" },
          ".greeting-title": { fontSize: "clamp(36px, 4.5vw, 54px)" },
          ".outfit-card-header": { padding: "18px 24px" },
          ".outfit-reasoning": { padding: "16px 24px" },
          ".outfit-actions": { padding: "16px 24px" },
          ".today-greeting .outfit-card": { marginTop: 32 },
          ".piece-visual": { maxHeight: 200 },
        },

        "@media (min-width: 1200px)": {
          ".today-hero": { gridTemplateColumns: "1fr 320px" },
        },

        "@media (min-width: 1440px)": {
          ".wardrobe-grid": {
            gridTemplateColumns: "repeat(5, 1fr)",
          },
        },
      }}
    />
  );
}
